# Generated by Django 4.2.4 on 2023-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_is_likes_like_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
